"""PDF export for solution reports."""

from dataclasses import dataclass, field
from pathlib import Path

from matplotlib import pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages


@dataclass(frozen=True)
class SolutionReport:
    """Content for a printable solution report."""

    title: str
    problem: str
    answer: str
    explanation: str
    steps: list[str] = field(default_factory=list)
    graph_paths: list[str | Path] = field(default_factory=list)


def export_solution_pdf(report: SolutionReport, output_path: str | Path) -> Path:
    """Export a solution report as a PDF using matplotlib's PDF backend."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with PdfPages(path) as pdf:
        figure = plt.figure(figsize=(8.27, 11.69))
        figure.text(0.08, 0.94, report.title, fontsize=18, weight="bold")
        y = 0.88
        y = _write_wrapped(figure, "Problem", report.problem, y)
        y = _write_wrapped(figure, "Final answer", report.answer, y)
        y = _write_wrapped(figure, "Explanation", report.explanation, y)
        if report.steps:
            y = _write_wrapped(figure, "Steps", "\n".join(report.steps), y)
        figure.text(0.08, 0.04, "Generated by IB Math AA HL ToolBox", fontsize=9)
        pdf.savefig(figure)
        plt.close(figure)

        for graph_path in report.graph_paths:
            image_path = Path(graph_path)
            if not image_path.exists():
                continue
            image = plt.imread(image_path)
            graph_figure, axis = plt.subplots(figsize=(8.27, 11.69))
            axis.imshow(image)
            axis.axis("off")
            axis.set_title(image_path.name)
            pdf.savefig(graph_figure)
            plt.close(graph_figure)

    return path


def _write_wrapped(figure: object, heading: str, text: str, y: float) -> float:
    figure.text(0.08, y, heading, fontsize=12, weight="bold")
    y -= 0.025
    for line in _wrap_lines(text, width=92):
        figure.text(0.08, y, line, fontsize=10)
        y -= 0.018
        if y < 0.10:
            break
    return y - 0.02


def _wrap_lines(text: str, width: int) -> list[str]:
    lines: list[str] = []
    for raw_line in text.splitlines() or [""]:
        words = raw_line.split()
        current = ""
        for word in words:
            candidate = f"{current} {word}".strip()
            if len(candidate) > width and current:
                lines.append(current)
                current = word
            else:
                current = candidate
        lines.append(current)
    return lines
